/**
 * build_provinces.js
 * Downloads Natural Earth admin-1 boundaries (50m resolution),
 * simplifies coordinates, and outputs a JS file for the game.
 * 
 * Run: node scripts/build_provinces.js
 */

const https = require('https');
const fs = require('fs');
const path = require('path');

const SOURCE_URL = 'https://raw.githubusercontent.com/nvkelso/natural-earth-vector/master/geojson/ne_10m_admin_1_states_provinces_lines.geojson';
const OUTPUT_PATH = path.join(__dirname, '..', 'provinces_geo.js');

function download(url) {
    return new Promise((resolve, reject) => {
        console.log('Downloading admin-1 boundaries...');
        let data = '';
        https.get(url, { headers: { 'User-Agent': 'Node' } }, (res) => {
            if (res.statusCode === 301 || res.statusCode === 302) {
                return download(res.headers.location).then(resolve).catch(reject);
            }
            res.on('data', chunk => data += chunk);
            res.on('end', () => {
                console.log(`Downloaded ${(data.length / 1024 / 1024).toFixed(1)}MB`);
                resolve(JSON.parse(data));
            });
        }).on('error', reject);
    });
}

function simplifyCoords(coords, tolerance) {
    // Douglas-Peucker simplification
    if (coords.length <= 2) return coords;
    
    let maxDist = 0, maxIdx = 0;
    const start = coords[0], end = coords[coords.length - 1];
    
    for (let i = 1; i < coords.length - 1; i++) {
        const d = pointLineDistance(coords[i], start, end);
        if (d > maxDist) { maxDist = d; maxIdx = i; }
    }
    
    if (maxDist > tolerance) {
        const left = simplifyCoords(coords.slice(0, maxIdx + 1), tolerance);
        const right = simplifyCoords(coords.slice(maxIdx), tolerance);
        return left.slice(0, -1).concat(right);
    }
    return [start, end];
}

function pointLineDistance(p, a, b) {
    const dx = b[0] - a[0], dy = b[1] - a[1];
    const lenSq = dx * dx + dy * dy;
    if (lenSq === 0) return Math.sqrt((p[0] - a[0]) ** 2 + (p[1] - a[1]) ** 2);
    let t = ((p[0] - a[0]) * dx + (p[1] - a[1]) * dy) / lenSq;
    t = Math.max(0, Math.min(1, t));
    const px = a[0] + t * dx, py = a[1] + t * dy;
    return Math.sqrt((p[0] - px) ** 2 + (p[1] - py) ** 2);
}

function roundCoord(c, decimals) {
    return [parseFloat(c[0].toFixed(decimals)), parseFloat(c[1].toFixed(decimals))];
}

async function main() {
    const geojson = await download(SOURCE_URL);
    console.log(`Raw features: ${geojson.features.length}`);
    
    const simplified = [];
    let totalPointsBefore = 0, totalPointsAfter = 0;
    
    for (const feature of geojson.features) {
        const geo = feature.geometry;
        if (!geo) continue;
        
        let lines = [];
        if (geo.type === 'LineString') {
            lines = [geo.coordinates];
        } else if (geo.type === 'MultiLineString') {
            lines = geo.coordinates;
        } else continue;
        
        const simplifiedLines = [];
        for (const line of lines) {
            totalPointsBefore += line.length;
            // Simplify with tolerance 0.01 degrees (~1km) for high accuracy
            let s = simplifyCoords(line, 0.01);
            s = s.map(c => roundCoord(c, 3));
            totalPointsAfter += s.length;
            if (s.length >= 2) simplifiedLines.push(s);
        }
        
        if (simplifiedLines.length > 0) {
            simplified.push(simplifiedLines);
        }
    }
    
    console.log(`Points: ${totalPointsBefore} → ${totalPointsAfter} (${((1 - totalPointsAfter/totalPointsBefore)*100).toFixed(0)}% reduction)`);
    console.log(`Line groups: ${simplified.length}`);
    
    // Output as JS
    const jsContent = `// Province borders — simplified Natural Earth admin-1 boundary lines
// Auto-generated by scripts/build_provinces.js
// Each entry is an array of line segments: [[[lon,lat],[lon,lat],...], ...]
const PROVINCE_BORDERS = ${JSON.stringify(simplified)};
`;
    
    fs.writeFileSync(OUTPUT_PATH, jsContent);
    const sizeMB = (fs.statSync(OUTPUT_PATH).size / 1024 / 1024).toFixed(2);
    console.log(`Written: ${OUTPUT_PATH} (${sizeMB}MB)`);
}

main().catch(console.error);
