// Generate province border lines from PROVINCE_POLYGONS
// This ensures borders and polygon fills are 100% consistent
const fs = require('fs');
const path = require('path');

const POLY_PATH = path.join(__dirname, '..', 'province_polygons.js');
const OUTPUT = path.join(__dirname, '..', 'provinces_geo.js');

// Load polygons
const txt = fs.readFileSync(POLY_PATH, 'utf8').replace('const ', 'var ');
eval(txt);

console.log(`Processing ${PROVINCE_POLYGONS.features.length} province polygons...`);

let allBorders = [];

PROVINCE_POLYGONS.features.forEach((feat, i) => {
    let rings = [];
    
    if (feat.geometry.type === 'Polygon') {
        rings = feat.geometry.coordinates;
    } else if (feat.geometry.type === 'MultiPolygon') {
        feat.geometry.coordinates.forEach(poly => {
            rings.push(...poly);
        });
    }
    
    let featureSegments = [];
    rings.forEach(ring => {
        if (ring.length >= 2) {
            featureSegments.push(ring);
        }
    });
    
    if (featureSegments.length > 0) {
        allBorders.push(featureSegments);
    }
});

console.log(`Generated ${allBorders.length} border features`);

let js = `// Province border lines — extracted from province_polygons.js\n// Auto-generated by scripts/build_province_borders.js\n// Each entry is an array of line segments: [[[lon,lat],[lon,lat],...], ...]\nconst PROVINCE_BORDERS = ${JSON.stringify(allBorders)};\n`;

fs.writeFileSync(OUTPUT, js);
console.log(`Written: ${OUTPUT} (${(fs.statSync(OUTPUT).size / 1024 / 1024).toFixed(2)} MB)`);
